name: CI

on:
  push:
    branches: [utama]
  pull_request:
    branches: [utama]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Jalankan skrip satu baris
        run: echo "Halo, dunia!"

      - name: Jalankan skrip multi-baris
        run: |
          echo "Tambahkan tindakan lain ke build"
          echo "Lakukan pengujian"
          echo "Build selesai"
